import type { NextPage } from 'next'
import { useEffect, useState } from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { MainLayout } from '@/components/Layout/index'
import Head from 'next/head'
import Box from '@mui/material/Box'
import HomePage from '@/containers/HomePage'
import Loading from '@/components/Loading/Loading'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
	const router = useRouter()

	const [pageLoading, setPageLoading] = useState(false)
	useEffect(() => {
		const handleStart = () => {
			setPageLoading(true)
		}
		const handleComplete = () => {
			setPageLoading(false)
		}

		router.events.on('routeChangeStart', handleStart)
		router.events.on('routeChangeComplete', handleComplete)
		router.events.on('routeChangeError', handleComplete)
	}, [router])
	return (
		<div>
			{pageLoading ? (
				<Loading />
			) : (
				<MainLayout className={styles.container}>
					<Head>
						<title>Create Next App</title>
						<meta name="description" content="Generated by create next app" />
						<link rel="icon" href="/favicon.ico" />
					</Head>
					<HomePage />
				</MainLayout>
			)}
		</div>
	)
}

export default Home
